cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: null
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: null
    scorsonejoe:
      email: scorsonejoseph4@gmail.com
      name: Owner
      password: $2b$12$eGobt8hNY.mS9qj0k9WRhO4vXCWrmXj0BbGxqDCQB6M9N4.CpsuCu
preauthorized:
  emails:
  - melsby@gmail.com
